version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    target-branch: main
    assignees:
      - thelime1
    versioning-strategy: increase
    commit-message:
      prefix: "build"
